controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
produit:
    path: /Produit.html.twig
    controller: src\Controller\ProduitController::index
